Sync dotfiles

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -9,6 +9,16 @@ VERBOSE=0
 QUIET=0
 FORCE=0
 
+# Check required commands
+errors=0
+for command in git realpath dirname; do
+  if ! which $command &>/dev/null; then
+    errors=1
+    echo "Could not find required command [1m$command[0m"
+  fi
+done
+[ "$errors" -ne 0 ] && exit 1
+
 function usage {
   echo "Usage: `basename $0` [options] COMMAND [args]"
   echo
