Sync dotfiles

diff --git a/bin/git-pull-all b/bin/git-pull-all
--- a/bin/git-pull-all
+++ b/bin/git-pull-all
@@ -4,18 +4,39 @@ filter_branches='/'
 
 while [ $# -gt 0 ]; do
   case "$1" in
-    -a) unset filter_branches;;
-    -f) filter_branches="$2"; shift;;
+    -a) filter_branches='$^';;
+    -x) filter_branches="$2"; shift;;
   esac
 
   shift
 done
 
-[ -n "$filter_branches" ] && filter_branches="| grep '$filter_branches'"
+current=`git describe --contains --all HEAD`
+branches=`git branch --color=never | cut -c 3-`
 
+if [ -z "$branches" ]; then
+  echo "No branches found!"
+  exit 1
+fi
 
-branches=`git branch --color=never $filter_branches | cut -c 3-`
+echo
+echo "Fetching updates..."
+git fetch -v || exit 1
+echo
 
 for branch in $branches; do
-  d
+  if [[ "$branch" =~ "$filter_branches" ]]; then
+    echo "Skipping [1;33m$branch[0m"
+  else
+    echo
+    git checkout "$branch" || continue
+    if ! git merge --ff-only HEAD@{u}; then
+      echo "Branch [1;31m$branch[0m could not be fast-forwarded."
+    fi
+  fi
 done
+echo
+
+if [ -n "$current" -a "$current" != "$branch" ]; then
+  git checkout "$current"
+fi
