Sync dotfiles

diff --git a/bin/ql b/bin/ql
--- a/bin/ql
+++ b/bin/ql
@@ -1,15 +1,15 @@
 #!/bin/bash
 
 PIPE=~/.quodlibet/control
-if [ ! -p $PIPE ] || ! lsof -n $PIPE &>/dev/null; then
-  echo "E: Quod Libet is not running."
-  exit 1
-fi
 
 CURRENT=~/.quodlibet/current
 
 function _ql {
   echo "$1" > $PIPE
+}
+
+function is_running {
+  [ -p $PIPE ] && lsof -n $PIPE &>/dev/null
 }
 
 function _song {
@@ -33,7 +33,32 @@ case "$command" in
     command="seek"
     argument="-0:5"
     ;;
+  start-hidden)
+    if is_running; then
+      echo "Quod Libet is already running."
+      exit
+    else
+      unset command
+      quodlibet &>/dev/null &
+      for i in `seq 1 20`; do
+        if is_running; then
+          command="hide-window"
+          break
+        fi
+        sleep 0.1
+      done
+
+      if [ -z "$command" ]; then
+        echo "E: Couldn't start Quod Libet, giving up."
+        exit 1
+      fi
+    fi
 esac
+
+if ! is_running; then
+  echo "E: Quod Libet is not running."
+  exit 1
+fi
 
 case "$command" in
   current)
