Sync dotfiles

diff --git a/bin/videb b/bin/videb
--- a/bin/videb
+++ b/bin/videb
@@ -1,42 +1,38 @@
 #!/bin/bash
 
-EDITOR=${EDITOR:-vi}
-
-if [[ -z "$1" ]]; then
-  echo "Syntax: $0 debfile"
+if [ -z "$1" ]; then
+  echo "Syntax: $0 FILE"
   exit 1
 fi
 
 DEBFILE="$1"
-TMPDIR=`mktemp -d /tmp/deb.XXXXXXXXXX` || exit 1
-OUTPUT=`basename "$DEBFILE" .deb`.modified.deb
+TMPDIR=$( mktemp -d /tmp/videb.XXXXXXXXXX ) || exit 1
+OUTPUT=$( basename "$DEBFILE" .deb ).modified.deb
 
-if [[ -e "$OUTPUT" ]]; then
-  echo "$OUTPUT exists."
-  rm -r "$TMPDIR"
+trap "rm -rf $TMPDIR" 0 1 2 3 9 15
+
+if [ -e "$OUTPUT" ]; then
+  echo "$OUTPUT already exists!"
   exit 1
 fi
 
-dpkg-deb -x "$DEBFILE" "$TMPDIR"
-dpkg-deb --control "$DEBFILE" "$TMPDIR"/DEBIAN
-
-if [[ ! -e "$TMPDIR"/DEBIAN/control ]]; then
-  echo DEBIAN/control not found.
-
-  rm -r "$TMPDIR"
-  exit 1
-fi
+dpkg-deb -vx "$DEBFILE" "$TMPDIR" || exit 1
+dpkg-deb --control "$DEBFILE" "$TMPDIR"/DEBIAN || exit 1
 
 CONTROL="$TMPDIR"/DEBIAN/control
 
-MOD=`stat -c "%y" "$CONTROL"`
-$EDITOR "$CONTROL"
-
-if [[ "$MOD" == `stat -c "%y" "$CONTROL"` ]]; then
-  echo Not modified.
-else
-  echo Building new deb...
-  dpkg -b "$TMPDIR" "$OUTPUT"
+if [ ! -f "$CONTROL" ]; then
+  echo "DEBIAN/control not found in $DEBFILE!"
+  exit 1
 fi
 
-rm -r "$TMPDIR"
+MOD=$( stat -c "%y" "$CONTROL" )
+
+sensible-editor "$CONTROL"
+
+if [ "$MOD" = "$( stat -c "%y" "$CONTROL" )" ]; then
+  echo "Not modified."
+else
+  echo
+  fakeroot -- dpkg -b "$TMPDIR" "$OUTPUT"
+fi
